"""comments for documents

Revision ID: 1c84da8fc6b2
Revises: 367c75eaf3c5
Create Date: 2025-10-03 14:26:25.600718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c84da8fc6b2'
down_revision = '367c75eaf3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comments_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comments_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_document_comments_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_comments_created_at'))

    op.drop_table('document_comments')
    # ### end Alembic commands ###
