"""documents add is_favorite

Revision ID: 367c75eaf3c5
Revises: 7f3ad3260eec
Create Date: 2025-10-03 12:12:31.730173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367c75eaf3c5'
down_revision = '7f3ad3260eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_items')
    op.drop_table('audits')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_documents_is_favorite'), ['is_favorite'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_is_favorite'))
        batch_op.drop_column('is_favorite')

    op.create_table('audits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nna_identificador', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nna_nombre', sa.VARCHAR(length=120), nullable=True),
    sa.Column('programa', sa.VARCHAR(length=50), nullable=False),
    sa.Column('revisor', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fecha_revision', sa.DATE(), nullable=False),
    sa.Column('condicion', sa.VARCHAR(length=15), nullable=False),
    sa.Column('puntaje_existencia', sa.INTEGER(), nullable=False),
    sa.Column('puntaje_actualizacion', sa.INTEGER(), nullable=False),
    sa.Column('estado_existencia', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estado_actualizacion', sa.VARCHAR(length=20), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audit_id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('aplica', sa.BOOLEAN(), nullable=False),
    sa.Column('existe', sa.BOOLEAN(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('verificador_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'codigo', name=op.f('uq_item_por_auditoria'))
    )
    # ### end Alembic commands ###
