"""audits: records and items

Revision ID: 45f76fc336cf
Revises: 8f2cd9377075
Create Date: 2025-08-03 22:36:15.021159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f76fc336cf'
down_revision = '8f2cd9377075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nna_identificador', sa.String(length=20), nullable=False),
    sa.Column('nna_nombre', sa.String(length=120), nullable=True),
    sa.Column('programa', sa.String(length=50), nullable=False),
    sa.Column('revisor', sa.String(length=120), nullable=False),
    sa.Column('fecha_revision', sa.Date(), nullable=False),
    sa.Column('condicion', sa.String(length=15), nullable=False),
    sa.Column('puntaje_existencia', sa.Integer(), nullable=False),
    sa.Column('puntaje_actualizacion', sa.Integer(), nullable=False),
    sa.Column('estado_existencia', sa.String(length=20), nullable=True),
    sa.Column('estado_actualizacion', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('aplica', sa.Boolean(), nullable=False),
    sa.Column('existe', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('verificador_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'codigo', name='uq_item_por_auditoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_items')
    op.drop_table('audits')
    # ### end Alembic commands ###
