"""documents add archived + folder_code

Revision ID: 5c61d92edf85
Revises: 1c84da8fc6b2
Create Date: 2025-10-03 16:30:35.570413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c61d92edf85'
down_revision = '1c84da8fc6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('folder_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_folder_code'), ['folder_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_folder_code'))
        batch_op.drop_index(batch_op.f('ix_documents_archived'))
        batch_op.drop_column('folder_code')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
