"""add satisfaction_surveys

Revision ID: 7f3ad3260eec
Revises: f32f6fc6f301
Create Date: 2025-09-15 21:45:33.364976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3ad3260eec'
down_revision = 'f32f6fc6f301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satisfaction_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respondida_en', sa.String(length=20), nullable=False),
    sa.Column('programa', sa.String(length=200), nullable=False),
    sa.Column('nombre_nna', sa.String(length=150), nullable=True),
    sa.Column('responsable_aplicacion', sa.String(length=150), nullable=True),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('p1_trato', sa.String(length=20), nullable=False),
    sa.Column('p2_info', sa.String(length=20), nullable=False),
    sa.Column('p3_tiempo', sa.String(length=20), nullable=False),
    sa.Column('p4_participacion', sa.String(length=20), nullable=False),
    sa.Column('p5_resultados', sa.String(length=20), nullable=False),
    sa.Column('p6_infraestructura', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('resultados_percibidos', sa.JSON(), nullable=True),
    sa.Column('firma_nna', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('satisfaction_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satisfaction_surveys_creado_en'), ['creado_en'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satisfaction_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satisfaction_surveys_creado_en'))

    op.drop_table('satisfaction_surveys')
    # ### end Alembic commands ###
