"""add reminders table

Revision ID: 851c3700098d
Revises: 5860cbbecd78
Create Date: 2025-10-29 00:12:53.556717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851c3700098d'
down_revision = '5860cbbecd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_owner_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_due_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_done'))

    op.drop_table('reminders')
    # ### end Alembic commands ###
