"""satisfaction survey

Revision ID: d09d6cc30645
Revises: 45f76fc336cf
Create Date: 2025-08-07 17:46:54.976565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09d6cc30645'
down_revision = '45f76fc336cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede', sa.String(length=20), nullable=True),
    sa.Column('programa', sa.String(length=60), nullable=True),
    sa.Column('respondido_por', sa.String(length=15), nullable=True),
    sa.Column('nombre_respondiente', sa.String(length=120), nullable=True),
    sa.Column('nombre_aplicador', sa.String(length=120), nullable=True),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('quiere_responder', sa.Boolean(), nullable=False),
    sa.Column('motivo_no_responde', sa.Text(), nullable=True),
    sa.Column('puntaje_total', sa.Integer(), nullable=True),
    sa.Column('categoria_final', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_answers')
    op.drop_table('surveys')
    # ### end Alembic commands ###
