"""audits_v2

Revision ID: f32f6fc6f301
Revises: d09d6cc30645
Create Date: 2025-09-11 18:13:42.616454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32f6fc6f301'
down_revision = 'd09d6cc30645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa', sa.String(length=100), nullable=False),
    sa.Column('nombre_revisor', sa.String(length=150), nullable=False),
    sa.Column('fecha_revision', sa.Date(), nullable=True),
    sa.Column('nombre_nna', sa.String(length=180), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_v2_existence',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('orden_ingreso', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('informe_derivacion', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('cert_nacimiento', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('carta_compromiso', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('ficha_ingreso', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('registro_actividades', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('puntaje_total', sa.Integer(), nullable=True),
    sa.Column('calificacion_existencia', sa.Enum('CUMPLE', 'NO_CUMPLE', name='aud_v2_cumple2'), nullable=True),
    sa.Column('observaciones_existencia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits_v2.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('audit_v2_updates',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('pii_fecha_elab', sa.Date(), nullable=True),
    sa.Column('pii_fecha_term', sa.Date(), nullable=True),
    sa.Column('pii_actualizado', sa.Enum('SI', 'NO', name='aud_v2_sino'), nullable=True),
    sa.Column('reg_act_ultima_fecha', sa.Date(), nullable=True),
    sa.Column('reg_act_actualizado', sa.Enum('SI', 'NO', name='aud_v2_sino'), nullable=True),
    sa.Column('tribunal_fecha_emision', sa.Date(), nullable=True),
    sa.Column('tribunal_actualizado', sa.Enum('SI', 'NO', 'NC', name='aud_v2_estado3'), nullable=True),
    sa.Column('calificacion_actualizacion', sa.Enum('CUMPLE', 'NO_CUMPLE', name='aud_v2_cumple2'), nullable=True),
    sa.Column('observaciones_actualizacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits_v2.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_v2_updates')
    op.drop_table('audit_v2_existence')
    op.drop_table('audits_v2')
    # ### end Alembic commands ###
